In [32]:
#gps 中 yaw 航向 弧度转角度  东为0 逆时针为正
import math
x = 1.03959632679490
r = math.degrees(x)
r

59.56448192265086

In [66]:
import open3d as o3d
import numpy as np

pcd = o3d.io.read_point_cloud('/Users/jinxuanchen/Files_Local/Point_image_fusion/kittidata/odometry/sequences/00/map_pcd_ds.pcd')
R = pcd.get_rotation_matrix_from_xyz((0, 0, -1.03959632679490))

In [67]:
R

array([[ 0.50656835,  0.86219981,  0.        ],
       [-0.86219981,  0.50656835,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [68]:
R1 = np.insert(R,3,values=0,axis=1)
R1 = np.insert(R1,3,values=[0,0,0,1],axis=0)
R1.shape

(4, 4)

In [69]:

points = np.loadtxt('/Users/jinxuanchen/Files_Local/Point_image_fusion/kittidata/odometry/sequences/00/map_pcd_ds.txt')
points

array([[ 9.43231888e+01, -3.91229820e+01, -6.22723389e+00,
         3.91670000e-02],
       [ 8.92993088e+01, -3.25923386e+01, -5.81851006e+00,
         0.00000000e+00],
       [ 4.03348274e+01, -2.86283140e-01, -6.30697584e+00,
         0.00000000e+00],
       ...,
       [-9.09745178e+01, -1.84064007e+00,  3.76742300e-01,
         0.00000000e+00],
       [-9.08582153e+01, -2.19387269e+00,  3.90237540e-01,
         0.00000000e+00],
       [-9.12774658e+01, -1.47203565e+00, -1.15901200e-02,
         0.00000000e+00]])

In [70]:
# points1 = points* R1
points1 = np.dot(points,R1)
points1

array([[ 8.15129693e+01,  6.15069711e+01, -6.22723389e+00,
         3.91670000e-02],
       [ 7.33373112e+01,  6.04836000e+01, -5.81851006e+00,
         0.00000000e+00],
       [ 2.06791801e+01,  3.46316585e+01, -6.30697584e+00,
         0.00000000e+00],
       ...,
       [-4.44978115e+01, -7.93706219e+01,  3.76742300e-01,
         0.00000000e+00],
       [-4.41343392e+01, -7.94492824e+01,  3.90237540e-01,
         0.00000000e+00],
       [-4.49690860e+01, -7.94451003e+01, -1.15901200e-02,
         0.00000000e+00]])

In [71]:
np.savetxt('/Users/jinxuanchen/Files_Local/Point_image_fusion/kittidata/odometry/sequences/00/map_pcd_ds_r.txt',points1,fmt='%.08f')

In [23]:
pcd.rotate(R, center=(0, 0, 0))

PointCloud with 94 points.

In [24]:
o3d.io.write_point_cloud("/Users/jinxuanchen/Files_Local/Point_image_fusion/kittidata/odometry/sequences/00/map_pcd_ds_r_1.pcd", pcd)

True